%ModuleHeaderCode
#include <aims/vector/vector.h>
%End

typedef AimsVector_FLOAT_4 Point4df;
typedef AimsVector_DOUBLE_3 Point3dd;
typedef AimsVector_FLOAT_3 Point3df;
typedef AimsVector_FLOAT_2 Point2df;
typedef AimsVector_S16_3 Point3d;
typedef AimsVector_S32_3 Point3dl;

Point3df vectProduct( const Point3df & v1, const Point3df & v2 );
Point3dd vectProduct( const Point3dd & v1, const Point3dd & v2 );

