# Specify sip v6 as the build system for the package.
[build-system]
requires = ["sip >=6, <7"]
build-backend = "sipbuild.api"

[tool.sip]
# project-factory = 'pyproject.py'

# Specify the PEP 566 metadata for the project.
[tool.sip.metadata]
name = "aimssip"

# Specify each set of bindings.
[tool.sip.bindings.aims]
include-dirs= ["/casa/host/build/include", "/usr/include/sigc++-2.0", "/usr/lib/x86_64-linux-gnu/sigc++-2.0/include", "/usr/include/libxml2"]
libraries = ["pyaims"]
library-dirs = ["/casa/host/build/lib"]
exceptions = true
concatenate = 16

# Configure the project itself.
[tool.sip.project]
sip-module = "PyQt6.sip"
dunder-init = false
target-dir = "/casa/host/build/python"
